# Generated by Django 4.1.5 on 2024-04-14 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fact_app', '0002_alter_customer_sex_alter_invoice_invoice_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('C', 'Contract'), ('D', 'Devis'), ('O', 'Other')], max_length=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_date', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(upload_to='documents/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fact_app.customer')),
                ('save_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
