# Generated by Django 4.1.5 on 2024-04-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0003_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='comments',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('C', 'Contract'), ('D', 'Devis'), ('A', 'Avis dimposition')], max_length=1),
        ),
    ]
